create table if not exists app
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING(200) unique
);

create table if not exists hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id    INTEGER REFERENCES APP (id) ON DELETE CASCADE,
    uri       VARCHAR(200) NOT NULL,
    ip        VARCHAR(64)  NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE
)