DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    text       VARCHAR(1000)                           NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_comments PRIMARY KEY (id)
);