CREATE TABLE IF NOT EXISTS participation_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id          BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester_id      BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status            VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_participation_requests PRIMARY KEY (id)
);