DROP TABLE IF EXISTS event_categories CASCADE;
DROP TABLE IF EXISTS event_locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS event_compilations CASCADE;


CREATE TABLE IF NOT EXISTS event_categories (
                                                id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                name VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS event_locations (
                                               id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               lat DOUBLE PRECISION NOT NULL,
                                               lon DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
                                      id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      title              VARCHAR(120) NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    category_id        BIGINT NOT NULL REFERENCES event_categories(id) ON DELETE RESTRICT,
    owner_id           BIGINT NOT NULL,
    location_id        BIGINT REFERENCES event_locations(id) ON DELETE SET NULL,
    initiator_id BIGINT NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date_time    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit  BIGINT NOT NULL DEFAULT 0,
    is_moderated       BOOLEAN DEFAULT TRUE,
    state              VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
                                            id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            title  VARCHAR(255) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
    );

CREATE TABLE IF NOT EXISTS event_compilations (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);