CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS event_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) UNIQUE,
    CONSTRAINT pk_event_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat DOUBLE PRECISION                        NOT NULL,
    lon DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_event_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(120),
    annotation           VARCHAR(2000)                            NOT NULL,
    description          VARCHAR(7000)                           NOT NULL,
    category_id          BIGINT REFERENCES event_categories (id) ON DELETE CASCADE,
    created_on           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_date_time      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    owner_id             BIGINT REFERENCES USERS (id) ON DELETE CASCADE,
    is_paid              BOOLEAN,
    participant_limit    INTEGER,
    published_on         TIMESTAMP WITHOUT TIME ZONE,
    is_moderated         BOOLEAN,
    state                VARCHAR(16)                             NOT NULL,
    location_id          BIGINT REFERENCES event_locations (id),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(100),
    pinned BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id          BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester_id      BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status            VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_participation_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    text       VARCHAR(1000)                           NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
